// Barrel exports — facilita import em paginas:
// import { Button, Card, KpiCard } from '../components/ui'

export { default as Avatar }            from './Avatar.jsx'
export { default as Badge }             from './Badge.jsx'
export { default as Button }            from './Button.jsx'
export { default as Card }              from './Card.jsx'
export { CardHeader, CardTitle, CardLabel } from './Card.jsx'
export { default as EmptyState }        from './EmptyState.jsx'
export { default as IconButton }        from './IconButton.jsx'
export { default as Input }             from './Input.jsx'
export { default as KpiCard }           from './KpiCard.jsx'
export { default as LanguageSwitcher }  from './LanguageSwitcher.jsx'
export { default as Modal }             from './Modal.jsx'
export { default as ProgressBar }       from './ProgressBar.jsx'
export { default as Search }            from './Search.jsx'
export { default as Skeleton }          from './Skeleton.jsx'
export { SkeletonText }                 from './Skeleton.jsx'
export { default as StatusIndicator }   from './StatusIndicator.jsx'
export { default as Switch }            from './Switch.jsx'
export { default as Table }             from './Table.jsx'
export { default as Tabs }              from './Tabs.jsx'
export { default as Toast }             from './Toast.jsx'
export { default as Tooltip }           from './Tooltip.jsx'
